spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/pawsitive
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pawsitive
    key-store-type: PKCS12
    key-alias: tomcat

jwt:
  secret: pawsitive_super_secret_key_2025_secure

custom:
  dev-mode: true
  dev-mode-user-token: dev-user-token
  dev-mode-shelter-token: dev-shelter-token
  dev-mode-user-email: dev@user.com
  dev-mode-shelter-email: dev@shelter.com